package br.com.zup.exception.internal;

import java.lang.System;

@kotlin.Metadata(mv = {1, 4, 2}, bv = {1, 0, 3}, k = 2, d1 = {"\u0000\u0014\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u000e\n\u0002\b\u0002\u001a\u001e\u0010\u0000\u001a\u00060\u0001j\u0002`\u00022\u0006\u0010\u0003\u001a\u00020\u00042\n\b\u0002\u0010\u0005\u001a\u0004\u0018\u00010\u0004\u00a8\u0006\u0006"}, d2 = {"makeException", "Ljava/lang/RuntimeException;", "Lkotlin/RuntimeException;", "exception", "", "message", "keymgr"})
public final class ExceptionFactoryKt {
    
    @org.jetbrains.annotations.NotNull()
    public static final java.lang.RuntimeException makeException(@org.jetbrains.annotations.NotNull()
    java.lang.String exception, @org.jetbrains.annotations.Nullable()
    java.lang.String message) {
        return null;
    }
}